// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCczsmYHGz0i8KRDt4EfoeNlXqn0yl79Xk',
    appId: '1:752845340048:web:b251afb8983a45e9aec715',
    messagingSenderId: '752845340048',
    projectId: 'traveller11222',
    authDomain: 'traveller11222.firebaseapp.com',
    storageBucket: 'traveller11222.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJh9FKjKjed5wWBQBvuQckeXzN1gusmns',
    appId: '1:752845340048:android:49e6094436b1a818aec715',
    messagingSenderId: '752845340048',
    projectId: 'traveller11222',
    storageBucket: 'traveller11222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcJ98bqdZDLjNdfgC5fAdlKQBxL6Ja9xQ',
    appId: '1:752845340048:ios:1b78e87829b52806aec715',
    messagingSenderId: '752845340048',
    projectId: 'traveller11222',
    storageBucket: 'traveller11222.appspot.com',
    iosClientId: '752845340048-kndkrjnuai8ti1f1n602qv0amp4imuaq.apps.googleusercontent.com',
    iosBundleId: 'com.wiktoriaholm.traveller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcJ98bqdZDLjNdfgC5fAdlKQBxL6Ja9xQ',
    appId: '1:752845340048:ios:1b78e87829b52806aec715',
    messagingSenderId: '752845340048',
    projectId: 'traveller11222',
    storageBucket: 'traveller11222.appspot.com',
    iosClientId: '752845340048-kndkrjnuai8ti1f1n602qv0amp4imuaq.apps.googleusercontent.com',
    iosBundleId: 'com.wiktoriaholm.traveller',
  );
}
